### ISSUE TITLE
vue-authenticate doesn't send data

### ISSUE THREAD

**Issue by Nati323** [dgrubelic/vue-authenticate#46] opened 2017-08-19 14:40 UTC
Hi, I'm trying to perform register action:

```
this.$auth.register(this.register).then((response) => {
				console.log('register');
			});
```
But I don't see any data sent to server in Chrome network developer tools
When I do `axios` normal request I can see the data that I transfer.

The request has been made, but no data sent

I also tried with normal object, nothing changed

**Comment by dgrubelic** [comment] 2017-09-01 06:28
Hi @Nati323,

I think I know where the problem is and I'll try to fix it next week.

**Comment by dgrubelic** [comment] 2017-09-24 08:40
Hi @Nati323 , can you gist your code on the server? Do you receive data on your API side?

**Comment by dgrubelic** [comment] 2017-10-07 14:18
I can't reproduce this issue. This is a screenshot taken with latest version `1.3.1`. 

![screen shot 2017-10-07 at 4 17 19 pm](https://user-images.githubusercontent.com/1304876/31308683-130da0c0-ab7b-11e7-8c61-68edf5514a31.png)

**Comment by dgrubelic** [comment] 2017-11-03 20:27
Can't confirm the issue, closing...

**Closed by dgrubelic** 2017-11-03 20:27 UTC

**Comment by pirmax** [comment] 2017-11-28 09:17
I have the same problem @Nati323 @dgrubelic...

**Comment by dgrubelic** [comment] 2017-11-28 10:05
I can't do anything if you don't gist your code, so... :)
