### ISSUE TITLE
This dependency was not found after upgrade to 1.3.0

### ISSUE THREAD

**Issue by arenasv86** [dgrubelic/vue-authenticate#58] opened 2017-09-24 15:29 UTC
Hi,

I've upgraded vue-authenticate to the last version (1.3.0) with Yarn.

After upgrade the console throws the error:
`This dependency was not found: vue-authenticate`

![captura de pantalla 2017-09-24 a las 17 26 39](https://user-images.githubusercontent.com/581171/30784043-ac706ab4-a14d-11e7-9c92-bf0569e1d274.png)

Any idea about this?

Thank you!

**Comment by koddr** [comment] 2017-09-24 22:43
@arenasv86 the same error with install from `npm`.

**Comment by jscheller** [comment] 2017-09-25 02:31
I believe the 1.30 release in the repository is missing the /dist folder. 

I was able to work around this by directly including the source like this...

`import VueAuthenticate from '../node_modules/vue-authenticate/src/authenticate.js'
`

However, I am still struggling with getting axios working properly with 1.3. When it loads, I'm getting...

```
Uncaught ReferenceError: $http is not defined
    at eval (eval at bindRequestInterceptor (options.js?32da:177), <anonymous>:1:10)
    at VueAuthenticate.bindRequestInterceptor (options.js?32da:23)
    at new VueAuthenticate (authenticate.js?2c82:48)
    at eval (main.js?1c90:79)
    at Object.<anonymous> (app.js:891)
    at __webpack_require__ (app.js:660)
    at fn (app.js:86)
    at Object.<anonymous> (app.js:1462)
    at __webpack_require__ (app.js:660)
    at app.js:709
```

Even though I've done a Vue.use(VueAxios, axios), so I'm not certain including the component this way is quite on target...

**Comment by jscheller** [comment] 2017-09-25 02:36
Oooooh. I think this detail of supplying Vue.axios instead of Vue.$http when I initialized got me there.

```
const vueAuth = new VueAuthenticate(Vue.axios, {
     // ....
}
```

**Comment by dgrubelic** [comment] 2017-09-25 06:10
Are you all using Yarn to install package? I'll see what the problem is, but i don't see /dist folder missing from repo in master branch.

**Comment by dgrubelic** [comment] 2017-09-25 11:24
Thanks for reporting this. 
Please install the latest version 1.3.1. There was `/dist` folder missing from the package because somehow folder was in `.gitignore`.

**Comment by arenasv86** [comment] 2017-09-26 07:48
For me, now works perfectly. 

Thank you very much @dgrubelic

**Comment by dgrubelic** [comment] 2017-09-26 09:47
Ok, great... Closing this issue. Regarding @jscheller issue, I believe there was similar issue so you can search for it.

**Closed by dgrubelic** 2017-09-26 09:47 UTC
